/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Returns the native module version. */
export declare function version(): string
/** A media timestamp. */
export declare class JsTimestamp {
  constructor(pts: number)
  static none(): JsTimestamp
  static zero(): JsTimestamp
  get pts(): number
  get isValid(): boolean
}
/** A zero-copy media frame buffer. */
export declare class JsMediaBuffer {
  /** Create a video buffer. */
  static video(data: Array<number>, pts: number): JsMediaBuffer
  /** Create an audio buffer. */
  static audio(data: Array<number>, pts: number): JsMediaBuffer
  /** Create an end-of-stream sentinel. */
  static eosVideo(): JsMediaBuffer
  get pts(): number
  get len(): number
  get isEmpty(): boolean
  get isKeyframe(): boolean
  get isEos(): boolean
  get mediaType(): string
  get codecId(): string
  /** Raw data as a Buffer. */
  data(): Array<number>
}
