/**
 * Placeholder type declarations for the native addon.
 *
 * This file is overwritten by `napi build` when the native addon is compiled.
 * It exists so that `tsc --noEmit` and IDEs work without first building Rust.
 *
 * DO NOT EDIT MANUALLY — regenerated by `npm run build:native:debug`.
 */

/** A media timestamp (PTS) — wraps a Rust `Timestamp` value. */
export class JsTimestamp {
  constructor(pts: number)
  static none(): JsTimestamp
  static zero(): JsTimestamp
  readonly pts: number
  readonly isValid: boolean
}

/** A zero-copy media frame buffer — wraps a Rust `MediaBuffer`. */
export class JsMediaBuffer {
  static video(data: Buffer | Uint8Array, pts: number): JsMediaBuffer
  static audio(data: Buffer | Uint8Array, pts: number): JsMediaBuffer
  static eosVideo(): JsMediaBuffer

  readonly pts: number
  readonly len: number
  readonly isEmpty: boolean
  readonly isKeyframe: boolean
  readonly isEos: boolean
  readonly mediaType: string
  readonly codecId: string

  data(): Buffer
}

/** Returns the native module version. */
export function version(): string
